name: $pluginName
main: $pluginMain
version: $version
api-version: '1.16'
depend:
  - Kotlin
  - InvFX

commands:
  bluemarble:
    usage: /bluemarble [args..]
    description: bluemarble plugin control